# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Harmander/CMPE_140/Lab 1/Lab 1.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Harmander/CMPE_140/Lab 1/Lab 1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Harmander/CMPE_140/Lab 1/Lab 1.srcs/sources_1/new/modules.v}
  {C:/Users/Harmander/CMPE_140/Lab 1/Lab 1.srcs/sources_1/new/factorial_DP.v}
  {C:/Users/Harmander/CMPE_140/Lab 1/Lab 1.srcs/sources_1/new/factorial_CU.v}
  {C:/Users/Harmander/CMPE_140/Lab 1/Lab 1.srcs/sources_1/new/led_mux.v}
  {C:/Users/Harmander/CMPE_140/Lab 1/Lab 1.srcs/sources_1/new/debounce2.v}
  {C:/Users/Harmander/CMPE_140/Lab 1/Lab 1.srcs/sources_1/new/clk_gen.v}
  {C:/Users/Harmander/CMPE_140/Lab 1/Lab 1.srcs/sources_1/new/bcd_to_7seg.v}
  {C:/Users/Harmander/CMPE_140/Lab 1/Lab 1.srcs/sources_1/new/factorial_CU_DP_wrap.v}
  {C:/Users/Harmander/CMPE_140/Lab 1/Lab 1.srcs/sources_1/new/factorial_machine_fpga.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Harmander/CMPE_140/Lab 1/Lab 1.srcs/sources_1/new/factorial_machine_fpga.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Harmander/CMPE_140/Lab 1/Lab 1.srcs/sources_1/new/factorial_machine_fpga.xdc}}]


synth_design -top factorial_machine_fpga -part xc7a100tcsg324-1


write_checkpoint -force -noxdef factorial_machine_fpga.dcp

catch { report_utilization -file factorial_machine_fpga_utilization_synth.rpt -pb factorial_machine_fpga_utilization_synth.pb }
