# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Van/CMPE_140/Lab 8/Lab 8.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Van/CMPE_140/Lab 8/Lab 8.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Van/CMPE_140/Lab 8/Lab 8.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {{C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/sources_1/new/memfile.dat}}
read_verilog -library xil_defaultlib {
  {C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/sources_1/new/dp_parts.v}
  {C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/sources_1/new/modules.v}
  {C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/sources_1/new/cu_parts.v}
  {C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/sources_1/new/factorial_DP.v}
  {C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/sources_1/new/factorial_CU.v}
  {C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/sources_1/new/register.v}
  {C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/sources_1/new/gpio_address_decoder.v}
  {C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/sources_1/new/datapath.v}
  {C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/sources_1/new/controlunit.v}
  {C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/sources_1/new/better_mux4.v}
  {C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/sources_1/new/factorial_CU_DP_wrap.v}
  {C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/sources_1/new/factorial_address_decoder.v}
  {C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/sources_1/new/soc_address_decoder.v}
  {C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/sources_1/new/mips.v}
  {C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/sources_1/new/mem_parts.v}
  {C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/sources_1/new/gpio_interface_wrapper.v}
  {C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/sources_1/new/factorial_wrapper.v}
  {C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/sources_1/new/utility.v}
  {C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/sources_1/new/soc_single_MIPS.v}
  {C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/sources_1/new/soc_single_MIPS_FPGA.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/constrs_1/imports/Lab_6_Stuff/mips_fpga.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Van/CMPE_140/Lab 8/Lab 8.srcs/constrs_1/imports/Lab_6_Stuff/mips_fpga.xdc}}]


synth_design -top soc_single_MIPS_FGPA -part xc7a100tcsg324-1


write_checkpoint -force -noxdef soc_single_MIPS_FGPA.dcp

catch { report_utilization -file soc_single_MIPS_FGPA_utilization_synth.rpt -pb soc_single_MIPS_FGPA_utilization_synth.pb }
